baseURL = "https://blog.mithril.be"
title = "Mithril"
language= "fr-fr"
theme = "hugo-geekblog"
disqusShortname = "blog-mithril-be"

[params]
  googleAnalyticMeasurementId = "G-B77PKPWQKK"
  
[taxonomies]
  author = "authors"
  tag = "tags"